CREATE TABLE "IncomingMapping" (
  "id" UUID NOT NULL,
  "type" TEXT NOT NULL,
  "cmsKey" TEXT NOT NULL,
  "cmsLabel" TEXT NOT NULL,
  "samoCode" TEXT NOT NULL,
  "samoName" TEXT NOT NULL,
  "adultCount" INTEGER,
  "childCount" INTEGER,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "IncomingMapping_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "IncomingMapping_type_cmsKey_key" ON "IncomingMapping"("type", "cmsKey");
CREATE INDEX "IncomingMapping_type_isActive_idx" ON "IncomingMapping"("type", "isActive");
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('72046e62-a0f5-4611-9a13-815158ab430d', 'room', 'standard', 'Standard', '3', 'Standard', NULL, NULL, 1) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('46b92665-8316-4e7f-9d76-900fbb1fb965', 'room', 'junior suite', 'Junior Suite', '4', 'Junior Suite', NULL, NULL, 2) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('2982361f-43f4-4596-a673-05fc8a98096b', 'room', 'suite', 'Suite', '5', 'Suite', NULL, NULL, 3) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('f8cf8b4b-f072-476b-91e0-4b401f32de6c', 'room', 'executive suite', 'Executive Suite', '6', 'Executive Suite', NULL, NULL, 4) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('0091d2bf-52cb-4942-9d0d-1860ad4f084f', 'room', 'one bedroom suite', 'One Bedroom Suite', '7', 'One Bedroom Suite', NULL, NULL, 5) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('a1cd00c4-3272-4a11-8f37-5bd8bcec91a7', 'room', 'one bedroom deluxe suite', 'One Bedroom Deluxe Suite', '8', 'One Bedroom Deluxe Suite', NULL, NULL, 6) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('324b9a70-88bf-41b9-80e3-d7df87774a6b', 'room', 'executive 15-18f', 'Executive 15-18F', '9', 'Executive 15-18F', NULL, NULL, 7) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('31400b79-5926-4f19-88cc-0e44ab325303', 'room', 'deluxe room', 'Deluxe Room', '10', 'Deluxe Room', NULL, NULL, 8) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('e43aa3df-8af2-46e3-81cc-ddec770de23d', 'room', 'family room', 'Family Room', '11', 'Family Room', NULL, NULL, 9) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('d283ff8a-7969-4c9e-885d-9dc355dae426', 'room', 'king suite', 'King Suite', '12', 'King Suite', NULL, NULL, 10) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('7a016dc9-5cec-4c48-8b98-57e10fc6ff1c', 'room', 'presidential suite', 'Presidential Suite', '13', 'Presidential Suite', NULL, NULL, 11) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('bdb134f9-2acd-4987-8d05-f235add0c625', 'room', 'single', 'Single', '14', 'Single', NULL, NULL, 12) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('461ac751-e80d-4a28-8802-86226ea1d572', 'room', 'standard with balcony', 'Standard With Balcony', '16', 'Standard With Balcony', NULL, NULL, 13) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('74a17a60-ee61-49bf-a843-0491694bdcab', 'room', 'senior suite', 'Senior Suite', '17', 'Senior Suite', NULL, NULL, 14) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('4367dc0c-de38-40ae-bdf1-6f2cbfd272b6', 'room', 'lux', 'Lux', '18', 'Lux', NULL, NULL, 15) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('3b66d005-c834-45eb-8ed4-7449bfb0fffb', 'placement', 'adults:1;children:0;placement:1adl', '1Adl', '3', '1Adl', 1, 0, 1) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('18a85466-145a-4813-8a65-f6a3d75c9b1c', 'placement', 'adults:1;children:1;placement:1adl+1chd(0-1.99)', '1Adl+1Chd(0-1.99)', '4', '1Adl+1Chd(0-1.99)', 1, 1, 2) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('6e73c6e9-1611-4c6d-8782-8b19ca541dd0', 'placement', 'adults:1;children:1;placement:1adl+1chd(2-5.99)', '1Adl+1Chd(2-5.99)', '5', '1Adl+1Chd(2-5.99)', 1, 1, 3) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('22df13ed-b593-4ddc-beb2-a99faa8741e6', 'placement', 'adults:1;children:1;placement:1adl+1chd(6-11.99)', '1Adl+1Chd(6-11.99)', '6', '1Adl+1Chd(6-11.99)', 1, 1, 4) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('955ac997-38ab-4530-aeee-cc308fc89dc4', 'placement', 'adults:1;children:2;placement:1adl+2chd(0-1.99)', '1Adl+2Chd(0-1.99)', '7', '1Adl+2Chd(0-1.99)', 1, 2, 5) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('45876abc-95be-497c-9aae-d730ccee5fc6', 'placement', 'adults:1;children:2;placement:1adl+2chd(0-1.99)(2-5.99)', '1Adl+2Chd(0-1.99)(2-5.99)', '8', '1Adl+2Chd(0-1.99)(2-5.99)', 1, 2, 6) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('e91103c6-1f7a-42f2-9a8e-78df7e2af1cf', 'placement', 'adults:1;children:2;placement:1adl+2chd(0-1.99)(6-11.99)', '1Adl+2Chd(0-1.99)(6-11.99)', '9', '1Adl+2Chd(0-1.99)(6-11.99)', 1, 2, 7) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('1778219b-adbb-499a-81fb-0e46f1e49261', 'placement', 'adults:1;children:2;placement:1adl+2chd(2-5.99)', '1Adl+2Chd(2-5.99)', '10', '1Adl+2Chd(2-5.99)', 1, 2, 8) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('263fc0af-27e7-4691-9e52-510dbe8ca11f', 'placement', 'adults:1;children:2;placement:1adl+2chd(2-5.99)(6-11.99)', '1Adl+2Chd(2-5.99)(6-11.99)', '11', '1Adl+2Chd(2-5.99)(6-11.99)', 1, 2, 9) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('4b8ebf81-3c17-44cd-a637-659bdf4c24f0', 'placement', 'adults:1;children:2;placement:1adl+2chd(6-11.99)', '1Adl+2Chd(6-11.99)', '12', '1Adl+2Chd(6-11.99)', 1, 2, 10) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('034bee8e-fb5a-41a1-a38b-ce8212982af4', 'placement', 'adults:2;children:0;placement:2adl', '2Adl', '13', '2Adl', 2, 0, 11) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('9e4c2b4d-0fe9-488c-a3df-0bd24f44feb6', 'placement', 'adults:2;children:1;placement:2adl+1chd(0-1.99)', '2Adl+1Chd(0-1.99)', '14', '2Adl+1Chd(0-1.99)', 2, 1, 12) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('b8acd8a3-840b-4520-aaf6-bb4ec82df7a9', 'placement', 'adults:2;children:1;placement:2adl+1chd(2-5.99)', '2Adl+1Chd(2-5.99)', '15', '2Adl+1Chd(2-5.99)', 2, 1, 13) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('0240d207-476b-4bf7-be9e-9883392f720f', 'placement', 'adults:2;children:1;placement:2adl+1chd(6-11.99)', '2Adl+1Chd(6-11.99)', '16', '2Adl+1Chd(6-11.99)', 2, 1, 14) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('24dc77f0-2afb-427e-a5fd-06618825465f', 'placement', 'adults:3;children:0;placement:3adl', '3Adl', '17', '3Adl', 3, 0, 15) ON CONFLICT ("type", "cmsKey") DO NOTHING;
INSERT INTO "IncomingMapping" ("id", "type", "cmsKey", "cmsLabel", "samoCode", "samoName", "adultCount", "childCount", "sortOrder") VALUES ('b624c068-39c6-43db-a45e-5c5685dc0b2b', 'placement', 'adults:2;children:0;placement:twin guest room', 'Twin Guest Room', '18', 'Twin Guest Room', 2, 0, 16) ON CONFLICT ("type", "cmsKey") DO NOTHING;
